# Generated by Django 5.2.1 on 2025-05-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mem0client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoryhistory',
            old_name='action',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='memoryhistory',
            old_name='new_value',
            new_name='new_memory',
        ),
        migrations.RenameField(
            model_name='memoryhistory',
            old_name='prev_value',
            new_name='old_memory',
        ),
        migrations.AddField(
            model_name='memoryhistory',
            name='actor_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='memoryhistory',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
